apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-vol1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-log-1
spec:
  resources:
    requests:
      storage: 50Mi
  accessModes:
    - ReadWriteMany
