apiVersion: storage.k8s.io.v1
kind: StorageClass
metadata:
  name: gcloud-pd-disk
  provisioner: kubernetes.io./gce-pd

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim-yo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gcloud-pd-disk
  resources:
    requests:
      storage: 50Mi

---
apiVersion: v1
kind: Pod
metadata:
  name: random-number-geneerator
spec:
  containers:
  - name: alpine
    image: alpine
    commnad: ['/bin/sh', '-c']
    args: ['shuf -i 0-100 -n 1 >> /opt/number.out']
    volumeMounts:
      - name: data-volume
    volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: myclaim-yo

